## Chapter 7 - Angular Momentum and Rotation
We'll use $\hbar=1$ for numerical results, this is standard practice, but it is important to remember.

In [1]:
from numpy import sqrt, pi, exp, angle
from qutip import *

Our usual spin operators (spin-1/2)

In [2]:
pz = basis(2,0)
mz = basis(2,1)
px = 1/sqrt(2)*(pz + mz)
mx = 1/sqrt(2)*(pz - mz)
py = 1/sqrt(2)*(pz + 1j*mz)
my = 1/sqrt(2)*(pz - 1j*mz)
Sx = 1/2.0*sigmax()
Sy = 1/2.0*sigmay()
Sz = 1/2.0*sigmaz()
Splus = Sx + 1j*Sy
Sminus = Sx - 1j*Sy

Define the spin-1 operators. We use J just to keep them apart. Could be S instead.

In [3]:
Jx = 1/sqrt(2)*Qobj([[0,1,0],[1,0,1],[0,1,0]])
Jy = 1/sqrt(2)*Qobj([[0,-1j,0],[1j,0,-1j],[0,1j,0]])
Jz = Qobj([[1,0,0],[0,0,0],[0,0,-1]])
Jplus = Jx + 1j*Jy # raising operator
Jminus = Jx - 1j*Jy # lowering operator

In [4]:
Jz

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]

## Rotations of spin-1/2

To define an exponentiated operator, we apply the `.expm()` method to the argument. So to write the rotation operator: 

$$\hat{R}_z(90^\circ) = e^{-i\frac{\pi}{2}\hat{S}_z}$$

we do the following. It looks a little odd to read since you might expect the `exp` to come first, but looks like this:

In [5]:
Rz90 = (-1j*pi/2*Sz).expm()

In [6]:
Rz90

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0.70710678-0.70710678j 0.        +0.j        ]
 [0.        +0.j         0.70710678+0.70710678j]]

In [7]:
Rz90*px

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.5-0.5j]
 [0.5+0.5j]]

Doesn't look like example 7.4 because it's not simplified. How to check:

In [8]:
exp(-1j*pi/4)*py

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.5-0.5j]
 [0.5+0.5j]]

 Yes, this agrees.

Can also use inner product:

In [9]:
py.dag()*Rz90*px

(0.7071067811865475-0.7071067811865475j)

In [10]:
abs(py.dag()*Rz90*px)

0.9999999999999999

In [11]:
angle(0.707 - 0.707j) == -pi/4

np.True_

## Find the spin-1 states (the eigenstates of the corresponding matrix)
According to the postulates, the allowed values of an observable are the eigenvalues with corresponding eigenstates.

We know the matrix representation of Jx, Jy, Jz in the Z-basis so we can find all 9 states (in the Z basis). Why nine? There are three possible values $\hbar$, 0, $-\hbar$ for each of three directions.

In [12]:
yevals, (yd,y0,yu) = Jy.eigenstates()
zevals, (zd,z0,zu) = Jz.eigenstates()
xevals, (xd,x0,xu) = Jx.eigenstates()

# Fix the signs to match book:
# (if first value of eigenstate is negative, flip all signs)
states = [xd, x0, xu, yd, y0, yu, zd, z0, zu]
states = [-s if s.full()[0][0]<0 else s for s in states]
# Python doesn't change the values in the list so we have 
# to replace the old values with the new ones:
[xd, x0, xu, yd, y0, yu, zd, z0, zu] = states

In [13]:
xd

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.5       ]
 [-0.70710678]
 [ 0.5       ]]

In [14]:
Rz90 = (-1j*pi/2*Jz).expm()

In [15]:
Rz90*xu == -1j*yu

True

In [16]:
Rz90*xu

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[3.06161700e-17-0.5j]
 [7.07106781e-01+0.j ]
 [3.06161700e-17+0.5j]]

In [17]:
yd

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.5+0.j        ]
 [ 0. -0.70710678j]
 [-0.5-0.j        ]]

In [18]:
abs(y0.dag()*Rz90*x0)

1.0

### 7.10 A spin-1 particle is measured to have $S_y=\hbar$. What is the probability that a subsequent measurement will yield $S_z=0$? $S_z=\hbar$? $S_z=-\hbar$?

In [19]:
abs(z0.dag()*yu)**2

0.4999999999999999

In [20]:
abs(zu.dag()*yu)**2

0.2500000000000002

In [21]:
abs(zd.dag()*yu)**2

0.2500000000000001

### 7.11 A spin-1 particle is measured to have $S_y=0$. What is the probability that a subsequent measurement will yield $S_x=-\hbar$?

In [22]:
abs(y0.dag()*xd)**2

0.4999999999999999

In [23]:
abs(xd.dag()*y0)**2

0.4999999999999999

### 7.13 $|\psi\rangle = \frac{1}{3}(2|1,1\rangle - i|1,0\rangle + 2|1,-1\rangle)$ Calculate expectation values of $S^2$, $S_y$, and $S_z$.

In [24]:
psi = (1/3)*(2*zu -1j*z0 +2*zd)
psi

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[0.66666667+0.j        ]
 [0.        -0.33333333j]
 [0.66666667+0.j        ]]

In [25]:
Jsquared = Jx*Jx + Jy*Jy + Jz*Jz
Jsquared

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=True
Qobj data =
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

In [26]:
psi.dag()*Jsquared*psi

(1.9999999999999993+0j)

In [27]:
psi.dag()*Jy*psi

0j

In [28]:
psi.dag()*Jz*psi

0j