## 2.3 Find the eigenvalues and vectors of J$_\theta$ for $\theta$=45

In [1]:
from qutip import *
from numpy import cos, sin, pi, deg2rad

In [2]:
qm = Qobj([[cos(pi/4)**2,cos(pi/4)*sin(pi/4)],[cos(pi/4)*sin(pi/4),sin(pi/4)**2]])

In [3]:
qm

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5  0.5]
 [ 0.5  0.5]]

In [4]:
qm.eigenstates()

(array([ 0.,  1.]),
 array([ Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[ 0.70710678]
  [-0.70710678]],
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[-0.70710678]
  [-0.70710678]]], dtype=object))

In [5]:
from numpy import sqrt, exp
1/sqrt(2)

0.70710678118654746

In [6]:
phi = 1.5
Jphi = Qobj([[exp(1j)*phi,0],[0,1]])
Jphi 

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.81045346+1.26220648j  0.00000000+0.j        ]
 [ 0.00000000+0.j          1.00000000+0.j        ]]

In [7]:
hvec = Qobj([[1],[0]])
hvec

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 1.]
 [ 0.]]

In [8]:
vvec = Qobj([[0],[1]])
vvec

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [ 1.]]

In [9]:
Jphi*hvec

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.81045346+1.26220648j]
 [ 0.00000000+0.j        ]]

In [10]:
Jphi*vvec

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [ 1.]]