# Lab 8 - Simple Harmonic Oscillator states
Problems from Chapter 12

In [2]:
from numpy import sqrt
from qutip import *

## Define the standard operators

In [3]:
N = 10  # pick a size for our state-space
a = destroy(N)
n = a.dag()*a

## Problem 12.1:

In [4]:
a*a.dag() - a.dag()*a

Quantum object: dims = [[10], [10]], shape = (10, 10), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -9.]]

## Problem 12.2:

In [5]:
n*a.dag() - a.dag()*n

Quantum object: dims = [[10], [10]], shape = (10, 10), type = oper, isherm = False
Qobj data =
[[ 0.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 1.          0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          1.41421356  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          1.73205081  0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          2.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          2.23606798  0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          2.44948974
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   2.6457513

In [6]:
n*a.dag() - a.dag()*n == a.dag()

True

## Problem 12.3 (use n=2 as a test-case):
To define $|2\rangle$ use the `basis(N,n)` command where `N` is the dimension of the vector, and `n` is the quantum number.

In [7]:
psi = basis(N,2)

In [8]:
psi

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]

## Problem 12.5 and 12.6:
These are simple, just view the matrix representation of the operators

## Problem 12.7:
First, define $\hat{X}$ and $\hat{P}$ operators

In [9]:
psi = 1/sqrt(2)*(basis(N,1)+basis(N,2))

## Problem 12.8:

In [10]:
psi = 1/sqrt(2)*(basis(N,2)+basis(N,4))