# Two-particle systems
An introduction to multi-particle spaces, starting with photon polarization states. This lab answers the question: How do we describe the state of two photons?

In [1]:
import matplotlib.pyplot as plt
from numpy import sqrt,pi,sin,cos,arange
from qutip import *

### The polarization states (in the HV-basis):

In [2]:
H = Qobj([[1],[0]])
V = Qobj([[0],[1]])
P45 = Qobj([[1/sqrt(2)],[1/sqrt(2)]])
M45 = Qobj([[1/sqrt(2)],[-1/sqrt(2)]])
R = Qobj([[1/sqrt(2)],[-1j/sqrt(2)]])
L = Qobj([[1/sqrt(2)],[1j/sqrt(2)]])

### Define two-particle states using the `tensor()` function:
Mathematically, we are taking the tensor product of two vectors. That product is a larger vector with twice as many entries as the individual state vectors. As long as we take the tensor products in the right order (i.e. always talking about photon 1 and photon 2 in that order) we can also make operators that act on two-photon states). In order to keep a consistent naming scheme, we'll call the first photon the **signal** photon and the second photon the **idler** photon. The names aren't particularly important but they come from the process we use in the lab: [SPDC](https://en.wikipedia.org/wiki/Spontaneous_parametric_down-conversion) 

In [10]:
HH = tensor(H,H)
HV = tensor(H,V)
VH = tensor(V,H)
VV = tensor(V,V)

In [11]:
# How do we represent HH? It is a vector with four elements.
HH

Quantum object: dims = [[2, 2], [1, 1]], shape = [4, 1], type = ket
Qobj data =
[[ 1.]
 [ 0.]
 [ 0.]
 [ 0.]]

Recall: The polarization measurement operator (for one photon):

In [9]:
Phv = H*H.dag() - V*V.dag()

The two-photon operator, measuring the **signal** photon, formed with the `tensor()` function and the `qeye()` function (identity operator)

In [12]:
Phv_s = tensor(Phv,qeye(2))
Phv_s

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

The two-photon operator, this time measuring the idler photon:

In [13]:
Phv_i = tensor(qeye(2),Phv)
Phv_i

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

The two-photon operators, projecting idler photon to H:

In [14]:
Ph = H*H.dag()
Ph_i = tensor(qeye(2),Ph)  # Ph for idler photon

And then for the signal photon:

In [15]:
Ph_s = tensor(Ph,qeye(2))  # Ph for signal photon

### Example: find the probability of measuring a horizontal idler photon if the system is prepared in the state $|HH\rangle$

In [16]:
HH.dag()*Ph_i*HH

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 1.]]

### Example: find the probability of measuring a horizontal idler photon in the state $|\psi\rangle = |H,+45\rangle$

In [17]:
psi = tensor(H,P45)  # the prepared state

In [18]:
psi.dag()*Ph_i*psi

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

### Example 8.2 prob. of measuring vertical signal and horizontal idler if $|\psi\rangle = |R,+45\rangle$

In [19]:
psi = tensor(R,P45)
psi.dag()*VH*VH.dag()*psi

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.25]]

## Entangled states:

In [20]:
phiPlus = 1/sqrt(2)*(HH + VV)

In [21]:
phiPlus.dag()*Ph_i*phiPlus  # probability of measuring a horizontal idler photon:

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

In [22]:
phiPlus.dag()*Ph_s*phiPlus  # probability of measuring a horizontal signal photon

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

## Now, find $P(H_s|H_i)$ (Example 8.5)

In [23]:
phiPlus.dag()*tensor(M45,P45)*tensor(M45,P45).dag()*phiPlus

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.]]

In [24]:
phiPlus.dag()*tensor(qeye(2),P45*P45.dag())*tensor(qeye(2),P45*P45.dag()).dag()*phiPlus

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

$P(H_s|H_i) = \frac{P(H_s,H_i)}{P(H_i)}$

In [45]:
0.5/0.5

1.0

## Perfect correlation between idler and signal... regardless of when they are measured.

## Using these states solve problems 8.2, 8.3, 8.7, 8.8