# Two-particle systems
An introduction to multi-particle spaces, starting with photon polarization states

In [3]:
import matplotlib.pyplot as plt
from numpy import sqrt,pi,sin,cos,arange
from qutip import *

###The polarization states (in the z-basis):

In [4]:
H = Qobj([[1],[0]])
V = Qobj([[0],[1]])
P45 = Qobj([[1/sqrt(2)],[1/sqrt(2)]])
M45 = Qobj([[1/sqrt(2)],[-1/sqrt(2)]])
R = Qobj([[1/sqrt(2)],[-1j/sqrt(2)]])
L = Qobj([[1/sqrt(2)],[1j/sqrt(2)]])

###Define two-particle states using the `tensor()` function:

In [29]:
HH = tensor(H,H)
HV = tensor(H,V)
VH = tensor(V,H)
VV = tensor(V,V)

The polarization measurement operator (for one photon):

In [30]:
Phv = H*H.dag() - V*V.dag()

The two-photon operator, measuring the signal photon, formed with the `tensor()` function and the `qeye()` function (identity operator)

In [32]:
Phv_s = tensor(Phv,qeye(2))
Phv_s

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]]

The two-photon operator, this time measuring the idler photon:

In [33]:
Phv_i = tensor(qeye(2),Phv)
Phv_i

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

The two-photon operators, projecting idler photon to H:

In [34]:
Ph = H*H.dag()
Ph_i = tensor(qeye(2),Ph)  # Ph for idler photon

And then for the signal photon:

In [35]:
Ph_s = tensor(Ph,qeye(2))  # Ph for signal photon

###Ex: find the probability of measuring a horizontal idler photon in the state $|HH\rangle$

In [36]:
HH.dag()*Ph_i*HH

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 1.]]

###Ex: find the probability of measuring a horizontal idler photon in the state $|\psi\rangle = |H,+45\rangle$

In [37]:
psi = tensor(H,P45)  # the prepared state

In [38]:
psi.dag()*Ph_i*psi

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

###Example 8.2 prob. of measuring vertical signal and horizontal idler if $|\psi\rangle = |R,+45\rangle$

In [39]:
psi = tensor(R,P45)
psi.dag()*VH*VH.dag()*psi

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.25]]

##Entangled states:

In [40]:
phiPlus = 1/sqrt(2)*(HH + VV)

In [41]:
phiPlus.dag()*Ph_i*phiPlus  # probability of measuring a horizontal idler photon:

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

In [42]:
phiPlus.dag()*Ph_s*phiPlus  # probability of measuring a horizontal signal photon

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

##Now, find $P(H_s|H_i)$ (Example 8.5)

In [43]:
phiPlus.dag()*tensor(M45,P45)*tensor(M45,P45).dag()*phiPlus

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.]]

In [44]:
phiPlus.dag()*tensor(qeye(2),P45*P45.dag())*tensor(qeye(2),P45*P45.dag()).dag()*phiPlus

Quantum object: dims = [[1], [1]], shape = [1, 1], type = oper, isherm = True
Qobj data =
[[ 0.5]]

$P(H_s|H_i) = \frac{P(H_s,H_i)}{P(H_i)}$

In [45]:
0.5/0.5

1.0

## Perfect correlation between idler and signal... regardless of when they are measured.

## Using these states solve problems 8.2, 8.3, 8.7, 8.8